// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/campaign" | "/daily" | "/login" | "/puzzles/[id]" | "/stats"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/health" | "/api/healthz" | "/api/puzzles/[id]" | "/api/puzzles/[id]/answer" | "/api/puzzles/[id]/hint" | "/api/puzzles/[id]/progress" | "/api/puzzles/[id]/submit" | "/api/puzzles/campaign" | "/api/puzzles/daily" | "/api/telemetry/client-error" | "/api/telemetry/web-vitals" | "/api/user/progress" | "/api/user/stats"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/health": {}
  "/api/healthz": {}
  "/api/puzzles/[id]": { "id": string; }
  "/api/puzzles/[id]/answer": { "id": string; }
  "/api/puzzles/[id]/hint": { "id": string; }
  "/api/puzzles/[id]/progress": { "id": string; }
  "/api/puzzles/[id]/submit": { "id": string; }
  "/api/puzzles/campaign": {}
  "/api/puzzles/daily": {}
  "/api/telemetry/client-error": {}
  "/api/telemetry/web-vitals": {}
  "/api/user/progress": {}
  "/api/user/stats": {}
  "/campaign": {}
  "/daily": {}
  "/login": {}
  "/puzzles/[id]": { "id": string; }
  "/stats": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
